apiVersion: v1
kind: Service
metadata:
  name: c2c-client
  namespace: c2c
  labels:
    app: c2c-client
spec:
  type: ClusterIP
  selector:
    app: c2c-client
  ports:
  - name: http
    port: 80
    targetPort: 80
