apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-ingress
  namespace: web
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: web-strip-chat@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: jhhomehub.gonetis.com
    http:
      paths:
      - path: /chat
        pathType: Prefix
        backend:
          service:
            name: chat
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-ingress
  namespace: web
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: web-strip-game@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: jhhomehub.gonetis.com
    http:
      paths:
      - path: /game
        pathType: Prefix
        backend:
          service:
            name: game
            port:
              number: 80
