apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ui
  namespace: monitoring
spec:
  entryPoints:
  - grafana
  routes:
  - match: Host(`jhhomehub.gonetis.com`)
    kind: Rule
    services:
    - name: monitoring-kube-prometheus-stack-grafana
      port: 80
