apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        port: 80
        expose:
          default: true
      websecure:
        port: 443
        expose:
          default: true
      mq:
        port: 15672
        expose:
          default: true
        exposedPort: 15672
        protocol: TCP
      argo:
        port: 8081
        expose:
          default: true
        exposedPort: 8081
        protocol: TCP
      grafana:
        port: 3000
        expose:
          default: true
        exposedPort: 3000
        protocol: TCP
      redisinsight:
        port: 5540
        expose:
          default: true
        exposedPort: 5540
        protocol: TCP
    additionalArguments:
    - "--entrypoints.mq.address=:15672"
    - "--entrypoints.argo.address=:8081"
    - "--entrypoints.grafana.address=:3000"
    - "--entrypoints.redisinsight.address=:5540"
