apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insight
  namespace: c2c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-insight
  template:
    metadata:
      labels:
        app: redis-insight
    spec:
      containers:
      - name: redis-insight
        image: redis/redisinsight:latest
        ports:
        - containerPort: 5540
          name: http
