apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insight
  namespace: c2c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-insight
  template:
    metadata:
      labels:
        app: redis-insight
    spec:
      containers:
      - name: redis-insight
        image: redis/redisinsight:latest
        env:
        - name: RI_ACCEPT_TERMS_AND_CONDITIONS
          value: "true"
        - name: RI_REDIS_HOST
          value: "redis"
        - name: RI_REDIS_PORT
          value: "6379"
        - name: RI_REDIS_USERNAME
          value: default
        - name: RI_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-auth
              key: redis-password
        ports:
        - containerPort: 5540
          name: http
        resources:
          requests:
            cpu: 300m
            memory: 1Gi
          limits:
            cpu: "1"
            memory: 2Gi
