apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redis-insight
  namespace: c2c
spec:
  entryPoints:
  - redisinsight
  routes:
  - match: Host(`jhhomehub.gonetis.com`)
    kind: Rule
    services:
    - name: redis-insight
      port: 5540
