apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - service.yaml
  - servicemonitor.yaml
  - statefulset.yaml
images:
  - name: ghcr.io/mohyeonman/c2c-ws-k3s
    newTag: sha-ec64345
