apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset.yaml
images:
  - name: ghcr.io/mohyeonman/c2c-ws-k3s
    newTag: sha-e61e60b8fb4e62ed1b4188bfd16e53840f625c86
