apiVersion: v1
kind: Service
metadata:
  name: c2c-ws
  namespace: c2c
spec:
  type: ClusterIP
  selector:
    app: c2c-ws
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: c2c-ws-headless
  namespace: c2c
spec:
  clusterIP: None
  selector:
    app: c2c-ws
  ports:
  - name: http
    port: 8080
    targetPort: 8080
